# The URL the site will be built for
base_url = "https://www.aldofunes.com"
default_language = "en"
build_search_index = true
theme = "tabi"
title = "Aldo Funes"
taxonomies = [{name = "tags", feed = true}]

[languages.es]
title = "Aldo Funes"
taxonomies = [{name = "tags", feed = true}]

[languages.pt-PT]
title = "Aldo Funes"
taxonomies = [{name = "tags", feed = true}]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
#highlight_theme = "dracula"
highlight_theme = "css"
highlight_themes_css = [
    { theme = "dracula", filename = "css/syntax.css" },
]
external_links_class = "external"


[extra]
# Put all your custom variables here
stylesheets = ["css/syntax.css"]

remote_repository_url = "https://github.com/aldofunes/blog"
remote_repository_git_platform = "auto"
remote_repository_branch = "main"
show_remote_changes = true
show_remote_source = true

favicon_emoji = "👾"